### ISSUE TITLE
Null value casted in string

### ISSUE THREAD

**Issue by lunika** [pomm-project/ModelManager#83]
I have a special case where a `<null>` value in my database is cast as an empty string in my entity. But it's not always the case, it only happens when the entity is loaded from a complex query

![screenshot-2017-10-31 symfony profiler 1](https://user-images.githubusercontent.com/767834/32228434-868e113e-be4e-11e7-9d6c-23e4c0fc2263.png)

On the screenshot it is the `subscription_history` table. The result is this one : 

![screenshot-2017-10-31 symfony profiler](https://user-images.githubusercontent.com/767834/32228647-1cbe9520-be4f-11e7-8571-bb70132b655b.png)

and in my database I have this value

![screenshot from 2017-10-31 14-56-15](https://user-images.githubusercontent.com/767834/32228606-fed34fb0-be4e-11e7-9e29-6d819903a74c.png)

the `origin` field is `null` but I have an empty string here. When I load this `subscription_history` record in a simple query (directly fron the `SubscriptionHistoryModel` I have no error.

I don't know if it's a foudation or model manager issue

**Comment by lunika** [comment]
Here is the raw result of the complex query 

![screenshot from 2017-10-31 15-25-14](https://user-images.githubusercontent.com/767834/32228890-c8634af6-be4f-11e7-9b31-f4ba18261553.png)

**Comment by chanmix51** [comment]
Unfortunately this is because the [converter uses PHP’s `str_getcsv()`](https://github.com/pomm-project/ModelManager/blob/2.0/sources/lib/Converter/PgEntity.php#L105) function in the `EntityConverter`. This builtin function implement the RFC4180 which has been made to convert CSV to `ms-application/excel` mime type. This RFC states all fieds are strings hence empty values are treated as empty strings (except for `str_getcsv('') which returns null, see [this discussion](https://stackoverflow.com/questions/42347304/distinct-empty-strings-from-nulls-in-a-csv-input) about it). 
The only way I see  to circumvent this problem would be to re-implement a finite-state CSV parser in PHP that would probably ruin all performance benefits.

**Comment by lunika** [comment]
Thanks for you answer. For this case I can use a work around and test if the value is `empty` instead of `NULL`. It can be `NULL` or a valid `uuid`. But your information is good to know :+1:
